# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    roles:
        label: Role
        scope: ApplyRoleFilter
        modelClass: October\Test\Models\Role
        nameFrom: name
        conditions: role_id in (:filtered)