# ===================================
#  Relation Behavior Config
# ===================================

roles:
    label: Roles
    list: @/plugins/october/test/models/role/columns.yaml
    form: @/plugins/october/test/models/role/fields.yaml
