# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    roles:
        label: Role
        scope: applyRoleFilter
        modelClass: October\Test\Models\Role
        nameFrom: name
    idRange:
        label: ID Range
        type: numberrange
        conditions: id >= ':min' and id <= ':max'
